image:
  repository: 855726270642.dkr.ecr.eu-north-1.amazonaws.com/duel-backend
  tag: 3190f32ca9866da6c200820ed9f3c6f905c1ab76 ## aws ecr describe-images --repository-name duel-backend --query 'imageDetails[].imageTags[0]'
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    memory: 768Mi
seatSecret:
  key: duel/dev/seat-secret
