image:
  repository: 855726270642.dkr.ecr.eu-north-1.amazonaws.com/duel-backend
  tag: b79b1d097f6f84db09a62fb34584ccc45af90e6f ## aws ecr describe-images --repository-name duel-backend --query 'imageDetails[].imageTags[0]'
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    memory: 768Mi
seatSecret:
  key: duel/dev/seat-secret
