image:
  repository: 855726270642.dkr.ecr.eu-north-1.amazonaws.com/duel-backend
  tag: c4afaa8b39b092b812130625eb81e3bf14b7d57c ## aws ecr describe-images --repository-name duel-backend --query 'imageDetails[].imageTags[0]'
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    memory: 768Mi
seatSecret:
  key: duel/dev/seat-secret
targetGroupName: duel-dev-backend
