image:
  repository: 855726270642.dkr.ecr.eu-north-1.amazonaws.com/duel-frontend
  tag: 6efa23e6daf57e094bbfade95b0a355c8edf030d # replaced by CI on the first build
resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 64Mi
